name: Contribution Space

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate contribution graph
        uses: kiaquila/comet-contribution-graph@v1
        with:
          username: gabivsv
          branch: output
          reduced: true
